version: '3.9'

services:
  medical-history-service:
    container_name: saludtechalpes-medical-history-service
    hostname: medical-history-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5002:5000"